name: CI

# only run when manually requested to
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build
        env:
          # Prevents warnings from being treated as errors
          CI: false

          # URL of backend API routes
          REACT_APP_API: https://api.palcode.dev
          # Base URL for socket.io
          REACT_APP_RUNNER: wss://runner.palcode.dev/xterm
          # URL for language server requests
          REACT_APP_LSP: wss://runner.palcode.dev/lsp

          # Firebase configuration (REACT_APP_F_*)
          REACT_APP_F_API_KEY: AIzaSyDvtCpVfSv_WyqODPmPlrYvGqCmlZZlbk8
          REACT_APP_F_AUTH_DOMAIN: palcode-ba70e.firebaseapp.com
          REACT_APP_F_DATABASE_URL: https://palcode-ba70e.firebaseio.com
          REACT_APP_F_PROJECT_ID: palcode-ba70e
          REACT_APP_F_STORAGE_BUCKET: palcode-ba70e.appspot.com
          REACT_APP_F_APP_ID: 1:1066769258920:web:472b48d2d97f99f99fa59d

          # publishable live key for Stripe
          REACT_APP_STRIPE: pk_live_51I2cPMAFoSADPMFq55uQelLJJa5yetLp0YzOFlogf338RtmSvIJxdVWbDAcz4BLfMyO73I5OF8rcj6aRgL4zryQ7003z5VjMXf

      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: Deploy to Firebase Hosting
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: palcode-ba70e
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
